name: Bug report
description: Create a report to help us improve cypress-cloud
labels: bug

body:
  - type: checkboxes
    attributes:
      label: |
        Before opening, please confirm:
      options:
        - label: I have searched for [duplicate or closed issues](https://github.com/currents-dev/cypress-cloud/issues) and [discussions](https://github.com/currents-dev/cypress-cloud/discussions).
          required: true
        - label: I will include a minimal, self-contained set of instructions for consistently reproducing the issue.
          required: true
        - label: I will attach a **full debug log**, otherwise the issue will be closed with no response.
          required: true

  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: textarea
    attributes:
      label: Environment information
      description: |
        We need to know what package versions you're using.

        Please run the following command inside your project and copy/paste the output below.

         **👉🏻 Run the command in the right environment 👈🏻**, e.g. if the problem is in CI environment, run it in the CI environment.

        ```
        npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages
        ```
      value: |
        <details>

        ```
        # Put output below this line


        ```

        </details>
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Details
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Setup and Command
      description: |
        - Your `cypress.config.js` file, including standalone plugins configuration.
        - The exact command or code snippet used to run the tests

    validations:
      required: true

  - type: textarea
    attributes:
      label: Full log and debug output
      description: |
        Enable the [debug mode](https://currents.dev/readme/integration-with-cypress/troubleshooting#enabling-debug-mode-for-cypress-cloud-1.9.0+) to provide more info - error messages and stack traces.

        - Follow [the guide to enable debug mode](https://currents.dev/readme/integration-with-cypress/troubleshooting#enabling-debug-mode-for-cypress-cloud-1.9.0+)
        - **👉🏻 Include the full log 👈🏻** - starting from running the command till receiving an error.
        - Attach a link / file for long outputs.

        Example:

        - `npx cypress-cloud run ... --cloud-debug`

        **Remove any sensitive data.**

      value: |
        <details>

        ```
        // Put your logs below this line


        ```

        </details>
    validations:
      required: true
