version: 2.1

jobs:
  cypress_tests:
    parallelism: 5
    docker:
      - image: cypress/browsers:latest
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: v5-deps-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v5-deps-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache
      - run:
          name: Build
          command: npm run build
      - run:
          name: Cypress Tests with @currents/cli
          command: |
            npm install @currents/cli
            npx currents run --record --parallel \
            --spec "./cypress/e2e*/*.spec.js" \
            --browser chrome --key $CURRENTS_RECORD_KEY \ 
            --tag currents-cli

workflows:
  cypress:
    jobs:
      - cypress_tests:
          context: currents
