name: Test Benchmark - @currents/cli

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    if: "contains(toJSON(github.event.commits.*.message), '[benchmark]')"
    strategy:
      fail-fast: false
      matrix:
        # run in parallel
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # populate commit message for merge commits
        # see ://currents.dev/readme/ci-setup/github-actions
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run Cypress with @currents/cli
        working-directory: ./examples/webapp
        env:
          FORCE_COLOR: 2 # for chalk tests
          CYPRESS_API_URL: https://cy-staging.currents.dev
          COMMIT_INFO_MESSAGE: "[@currents/cli] ${{ github.event.head_commit.message }}"
        run: |
          npm install cy2@4.0.7-beta.2
          npx cy2 run --record --parallel \
          --spec "./cypress/benchmark_short/*.spec.js" \
          --browser chrome --key ${{ secrets.CURRENTS_STAGING_RECORD_KEY }} \ --ci-build-id "cy-${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}}" --tag currents-cli,gha
