name: e2e-smoke-windows

on:
  push:

jobs:
  build:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    runs-on: windows-latest
    env:
      DEBUG: currents:*

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Link monorepo packages
        run: npm install

      - name: Run Cypress with cypress-cloud
        working-directory: ./examples/webapp
        env:
          CURRENTS_API_URL: http://localhost:1234
        run: |
          npx cypress-cloud run --help
